CREATE TABLE TB_ENDERECOS (
    IDE_ENDERECO SERIAL PRIMARY KEY,
    DES_LOGRADOURO VARCHAR(255),
    NUM_ENDERECO VARCHAR(50),
    DES_COMPLEMENTO VARCHAR(255),
    DES_BAIRRO VARCHAR(255),
    DES_CIDADE VARCHAR(255),
    DES_ESTADO VARCHAR(255),
    NUM_CEP VARCHAR(20)
);

CREATE TABLE TB_TIPO_USUARIOS (
    IDE_TIPO_USUARIO SERIAL PRIMARY KEY,
    DES_TIPO_USUARIO VARCHAR(255)
);

CREATE TABLE TB_USUARIOS (
    IDE_USUARIO SERIAL PRIMARY KEY,
    NOM_COMPLETO VARCHAR(255) NOT NULL,
    IDE_ENDERECO BIGINT NULL,
    DES_EMAIL VARCHAR(255) NOT NULL,
    NOM_LOGIN VARCHAR(255) NOT NULL,
    DES_SENHA VARCHAR(255) NOT NULL,
    IDE_TIPO_USUARIO BIGINT NOT NULL,
    DTA_ULT_ALTERACAO TIMESTAMP,
    CONSTRAINT FK_USUARIOS_ENDERECO FOREIGN KEY (IDE_ENDERECO) REFERENCES TB_ENDERECOS(IDE_ENDERECO) ON DELETE SET NULL,
    CONSTRAINT FK_USUARIOS_TIPO_USUARIO FOREIGN KEY (IDE_TIPO_USUARIO) REFERENCES TB_TIPO_USUARIOS(IDE_TIPO_USUARIO) ON DELETE SET NULL
);

CREATE TABLE TB_RESTAURANTES (
    IDE_RESTAURANTE SERIAL PRIMARY KEY,
    NOM_RESTAURANTE VARCHAR(255),
    TIPO_COZINHA VARCHAR(255),
    IDE_ENDERECO BIGINT NULL,
    IDE_USUARIO BIGINT NOT NULL,
    CONSTRAINT FK_RESTAURANTE_ENDERECO FOREIGN KEY (IDE_ENDERECO) REFERENCES TB_ENDERECOS(IDE_ENDERECO) ON DELETE SET NULL,
    CONSTRAINT FK_RESTAURANTE_USUARIO FOREIGN KEY (IDE_USUARIO) REFERENCES TB_USUARIOS(IDE_USUARIO) ON DELETE SET NULL
);

CREATE TABLE TB_CARDAPIO (
    IDE_CARDAPIO SERIAL PRIMARY KEY,
    IDE_RESTAURANTE BIGINT NULL,
    CONSTRAINT FK_CARDAPIO_RESTAURANTE FOREIGN KEY (IDE_RESTAURANTE) REFERENCES TB_RESTAURANTES(IDE_RESTAURANTE) ON DELETE SET NULL
);

CREATE TABLE TB_ITENS_CARDAPIOS (
    IDE_ITEM SERIAL PRIMARY KEY,
    NOM_ITEM VARCHAR(255) NOT NULL,
    DES_ITEM VARCHAR(255) NOT NULL,
    VLR_ITEM DECIMAL(10, 2) NOT NULL,
    DES_FOTO VARCHAR(255),
    STA_LOCAL BOOLEAN NOT NULL,
    IDE_CARDAPIO BIGINT NOT NULL,
    CONSTRAINT FK_ITEM_CARDAPIO FOREIGN KEY (IDE_CARDAPIO) REFERENCES TB_CARDAPIO(IDE_CARDAPIO) ON DELETE SET NULL
);

CREATE TABLE TB_FUNCIONAMENTO (
    IDE_FUNCIONAMENTO SERIAL PRIMARY KEY,
    DTA_SEMANA VARCHAR(20),
    HORA_ABERTURA TIME,
    HORA_FECHA TIME,
    IDE_RESTAURANTE BIGINT NULL,
    CONSTRAINT FK_FUNCIONAMENTO_RESTAURANTE FOREIGN KEY (IDE_RESTAURANTE) REFERENCES TB_RESTAURANTES(IDE_RESTAURANTE) ON DELETE SET NULL
);

INSERT INTO TB_TIPO_USUARIOS (DES_TIPO_USUARIO) VALUES
    ('CLIENTE'),
    ('DONO_RESTAURANTE'),
    ('ADMIN');