SET REFERENTIAL_INTEGRITY FALSE;

DROP TABLE TB_ITENS_CARDAPIOS;

DROP TABLE TB_CARDAPIO;

DROP TABLE TB_FUNCIONAMENTO;

DROP TABLE TB_RESTAURANTES;

DROP TABLE TB_USUARIOS;

DROP TABLE TB_ENDERECOS;

DROP TABLE TB_TIPO_USUARIOS;

SET REFERENTIAL_INTEGRITY TRUE;